port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info

proxies:
  - name: "俄罗斯1"
    type: ss
    server: 185.242.86.156
    port: 54170
    cipher: chacha20-ietf-poly1305
    password: "36ZChEabuSfKjfQEvcJ4HDV"

proxy-groups:
  - name: "🚀 代理"
    type: url-test
    proxies:
      - "俄罗斯1"
    url: "http://www.gstatic.com/generate_204"
    interval: 300

rules:
  - GEOIP,CN,DIRECT
  - MATCH,🚀 代理
