port: 7890
socks-port: 7891
allow-lan: false
mode: rule
log-level: info

proxy-providers:
  auto-nodes:
    type: http
    url: "https://fastly.jsdelivr.net/gh/yxx0234/url@main/provider.yaml"
    path: ./proxy-providers/auto-nodes.yaml
    interval: 3600
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 300

proxy-groups:
  - name: "🚀 自动选择"
    type: url-test
    use:
      - auto-nodes
    url: "http://www.gstatic.com/generate_204"
    interval: 300

rules:
  - GEOIP,CN,DIRECT
  - MATCH,🚀 自动选择